import Head from "next/head";
import Navbar from "../components/Navbar";
import Banner from "../components/Banner";
import About from "../components/About";
import Project from "../components/Project";
import Contact from "../components/Contact";
export default function Home() {
	return (
		<div>
			<Head>
				<title>PutuSaputra</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="portofolio.ico" />
			</Head>
			<Navbar />
			<Banner />
			<About />
			<Project />
			<Contact/>
		</div>
	);
}
